'use strict';
exports.BattleLearnsets = {
	pyrix: {learnset: {
	quiverdance: ["7M"],
	lightofruin: ["7M"],
	hiddenpower: ["7M"],
	protect: ["7M"],
	substitute: ["7M"],
	rest: ["7M"],
	fireblast: ["7M"],
	energyball: ["7M"],
	flamethrower: ["7M"],
	moonblast: ["7M"],
	sunnyday: ["7M"],
	nastyplot: ["7M"],
	calmmind: ["7M"],
	hiddenpower: ["7M"],
	hypnosis: ["7M"],
	chargebeam: ["7M"],
	psyshock: ["7M"],
	earthpower: ["7M"],
	willowisp: ["7M"],
	return: ["7M"],
	frustration: ["7M"],
	toxic: ["7M"],
	smokescreen: ["7M"],
	flatter: ["7M"],
	hex: ["7M"],
	taunt: ["7M"],
	},
};
