'use strict';

exports.BattlePokedex = {
	pyrix: {
		num: -9000,
		species: "Pyrix",
		types: ["Fire", "Fairy"],
		baseStats: {hp: 110, atk: 60, def: 85, spa: 120, spd: 90, spe: 70},
		abilities: {0: "Intimidate", 1: "Storm Drain", H: "Simple"},
		heightm: 0.7,
		weightkg: 22.2,
		color: "Red",
		eggGroups: ["Amorphous"],
	},
	malwarrior: {
		num: -9001,
		species: "Malwarrior",
		baseForme: "Observer",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 60, atk: 50, def: 150, spa: 50, spd: 150, spe: 60},
		abilities: {0: "Modify Program"},
		heightm: 1.7,
		weightkg: 53,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Mage", "Fighter"],
	},
	malwarriormage: {
		num: -9001,
		species: "Malwarrior-Mage",
		baseSpecies: "Malwarrior",
		forme: "Mage",
		formeLetter: "W",
		types: ["Steel", "Ghost"],
		baseStats: {hp: 60, atk: 150, def: 50, spa: 150, spd: 50, spe: 60},
		abilities: {0: "Stance Change"},
		heightm: 1.7,
		weightkg: 53,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	malwarriorfighter: {
		num: -9001,
		species: "Malwarrior-Fighter",
		baseSpecies: "Malwarrior",
		forme: "Fighter",
		formeLetter: "P",
		types: ["Steel", "Ghost"],
		baseStats: {hp: 60, atk: 150, def: 50, spa: 150, spd: 50, spe: 60},
		abilities: {0: "Stance Change"},
		heightm: 1.7,
		weightkg: 53,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
};
