'use strict';
exports.BattleLearnsets = {
	pyrix: {
		learnset: {
			quiverdance: ["7M"],
			wish: ["7M"],
			solarbeam: ["7M"],
			healingwish: ["7M"],
			lightofruin: ["7M"],
			hiddenpower: ["7M"],
			protect: ["7M"],
			substitute: ["7M"],
			rest: ["7M"],
			fireblast: ["7M"],
			energyball: ["7M"],
			flamethrower: ["7M"],
			moonblast: ["7M"],
			sunnyday: ["7M"],
			nastyplot: ["7M"],
			calmmind: ["7M"],
			hypnosis: ["7M"],
			chargebeam: ["7M"],
			psyshock: ["7M"],
			earthpower: ["7M"],
			willowisp: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			toxic: ["7M"],
			smokescreen: ["7M"],
			flatter: ["7M"],
			hex: ["7M"],
			taunt: ["7M"],
			cosmicpower: ["7M"],
			sleeptalk: ["7M"],
		},
	},
	naucess: {
		learnset: {
			gunkshot: ["7M"],
			poisonjab: ["7M"],
			playrough: ["7M"],
			swordsdance: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			hiddenpower: ["7M"],
			substitute: ["7M"],
			drainpunch: ["7M"],
			rest: ["7M"],
			sleeptalk: ["7M"],
			flareblitz: ["7M"],
			firepunch: ["7M"],
			flamecharge: ["7M"],
			landswrath: ["7M"],
			protect: ["7M"],
			attackorder: ["7M"],
			healorder: ["7M"],
			toxic: ["7M"],
			lovelykiss: ["7M"],
			sweetkiss: ["7M"],
			diamondstorm: ["7M"],
			knockoff: ["7M"],
			suckerpunch: ["7M"],
			icepunch: ["7M"],
			thunderpunch: ["7M"],
			magicalpunch: ["7M"],
		},
	},
	baroon: {
		learnset: {
			endure: ["7M"],
			mirrorcoat: ["7M"],
			blizzard: ["7M"],
			dig: ["7M"],
			dragonrage: ["7M"],
			hyperbeam: ["7M"],
			lightscreen: ["7M"],
			hydropump: ["7M"],
			earthquake: ["7M"],
			hiddenpower: ["7M"],
			protect: ["7M"],
			substitute: ["7M"],
			rest: ["7M"],
			stoneedge: ["7M"],
			rockpolish: ["7M"],
			stealthrock: ["7M"],
			slackoff: ["7M"],
			rockslide: ["7M"],
			earthpower: ["7M"],
			icebeam: ["7M"],
			scald: ["7M"],
			waterfall: ["7M"],
			toxic: ["7M"],
			thunderwave: ["7M"],
			bounce: ["7M"],
			refresh: ["7M"],
			spikes: ["7M"],
			detect: ["7M"],
			ironhead: ["7M"],
			rocktomb: ["7M"],
			bulkup: ["7M"],
			workup: ["7M"],
			calmmind: ["7M"],
		},
	},
	// TODO: Make movesets for these pokemon
	malwar: {
		learnset: {
			sketch: ["7M"],
		},
	},
	zeron: {
		learnset: {
			sketch: ["7M"],
		},
	},
	chivalroot: {
		learnset: {
			sketch: ["7M"],
		},
	},
	poseident: {
		learnset: {
			sketch: ["7M"],
		},
	},
	fusionvxn: {
		learnset: {
			sketch: ["7M"],
		},
	},
	scarablade: {
		learnset: {
			sketch: ["7M"],
		},
	},
	gigamole: {
		learnset: {
			sketch: ["7M"],
			pitfall: ["7M"],
		},
	},
	scalwyng: {
		learnset: {
			sketch: ["7M"],
		},
	},
};
