'use strict';

exports.BattlePokedex = {
	pyrix: {
		num: -9000,
		species: "Pyrix",
		types: ["Fire", "Fairy"],
		baseStats: {hp: 90, atk: 60, def: 85, spa: 120, spd: 55, spe: 90},
		abilities: {0: "Blaze", H: "Simple"},
		genderRatio: {M: 0.875, F: 0.125},
		heightm: 0.5,
		weightkg: 0.1,
		color: "Red",
		eggGroups: ["Amorphous"],
	},
	malwar: {
		num: -9001,
		species: "Malwar",
		baseForme: "Observer",
		types: ["Electric", "Normal"],
		baseStats: {hp: 100, atk: 75, def: 120, spa: 75, spd: 120, spe: 100},
		abilities: {0: "Frisk"},
		gender: "N",
		heightm: 1.7,
		weightkg: 1,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Mage", "Fighter"],
	},
	malwarmage: {
		num: -9001,
		species: "Malwar-Mage",
		baseSpecies: "Malwar",
		forme: "Mage",
		formeLetter: "M",
		types: ["Electric", "Psychic"],
		baseStats: {hp: 100, atk: 20, def: 120, spa: 160, spd: 50, spe: 100},
		abilities: {0: "Magical Power"},
		gender: "N",
		heightm: 1.7,
		weightkg: 1.5,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	malwarfighter: {
		num: -9001,
		species: "Malwar-Fighter",
		baseSpecies: "Malwar",
		forme: "Fighter",
		formeLetter: "F",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 100, atk: 160, def: 50, spa: 20, spd: 120, spe: 100},
		abilities: {0: "Huge Power"},
		gender: "N",
		heightm: 1.7,
		weightkg: 2,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	naucess: {
		num: -9002,
		species: "Naucess",
		types: ["Fairy", "Poison"],
		baseStats: {hp: 110, atk: 130, def: 60, spa: 60, spd: 60, spe: 75},
		abilities: {0: "Queenly Majesty", 1: "Iron Fist", H: "Firestarter"},
		gender: "F",
		heightm: 1,
		weightkg: 15,
		color: "Purple",
		eggGroups: ["Human-Like"],
	},
	chivalroot: {
		num: -9003,
		species: "Chivalroot",
		types: ["Grass", "Steel"],
		baseStats: {hp: 75, atk: 85, def: 120, spa: 30, spd: 110, spe: 80},
		abilities: {0: "Overgrow", H: "Justified"},
		genderRatio: {M: 0.875, F: 0.125},
		heightm: 3,
		weightkg: 100,
		color: "Green",
		eggGroups: ["Human-Like", "Field"],
	},
	poseident: {
		num: -9004,
		species: "Poseident",
		types: ["Water", "Fighting"],
		baseStats: {hp: 80, atk: 120, def: 75, spa: 60, spd: 55, spe: 110},
		abilities: {0: "Torrent", H: "Defiant"},
		genderRatio: {M: 0.875, F: 0.125},
		heightm: 1.5,
		weightkg: 5,
		color: "Blue",
		eggGroups: ["Water 1"],
	},
	zeron: {
		num: -9005,
		species: "Zeron",
		types: ["Ice", "Flying"],
		baseStats: {hp: 55, atk: 70, def: 95, spa: 120, spd: 80, spe: 55},
		abilities: {0: "Snow Cloak", 1: "Magic Guard", H: "Unaware"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 1.2,
		weightkg: 0.8,
		color: "Blue",
		eggGroups: ["Field"],
	},
	fusionvxn: {
		num: -9006,
		species: "Fusion VxN",
		types: ["Grass", "Electric"],
		baseStats: {hp: 255, atk: 255, def: 255, spa: 255, spd: 255, spe: 255},
		abilities: {0: "Corruption"},
		gender: "N",
		heightm: 100,
		weightkg: 9999,
		color: "Unknown",
		eggGroups: ["Undiscovered"],
	},
	baroon:{
		num: -9007,
		species: "Baroon",
		types: ["Water", "Ground"],
		baseStats: {hp: 230, atk: 90, def: 150, spa: 110, spd: 90, spe: 70},
		abilities: {0: "Sturdy", 1: "Water Veil", H: "Rough Skin"},
		genderRatio: {M: 0.9, F: 0.1},
		heightm: 1.7,
		weightkg: 60,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	scarablade:{
		num: -9008,
		species: "Scarablade",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 50, atk: 95, def: 65, spa: 50, spd: 50, spe: 85},
		abilities: {0: "Swarm", H: "Adaptability"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 0.5,
		weightkg: 5,
		color: "Green",
		eggGroups: ["Bug", "Dragon"],
	},
	gigamole:{
		num: -9009,
		species: "Gigamole",
		types: ["Electric", "Ground"],
		baseStats: {hp: 60, atk: 105, def: 75, spa: 30, spd: 60, spe: 95},
		abilities: {0: "Static", H: "Serene Grace"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 1.5,
		weightkg: 7,
		color: "Brown",
		eggGroups: ["Field"],
	},
	scalwyng:{
		num: -9010,
		species: "Scalwyng",
		types: ["Dragon", "Fairy"],
		baseStats: {hp: 150, atk: 120, def: 60, spa: 90, spd: 60, spe: 120},
		abilities: {0: "Pressure", H: "Illusion"},
		gender: "N",
		heightm: 0.5,
		weightkg: 0.5,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	alkalyse:{
		num: -9011,
		species: "Alkalyse",
		types: ["Steel", "Poison"],
		baseStats: {hp: 80, atk: 50, def: 150, spa: 100, spd: 150, spe: 120},
		abilities: {0: "Corrosion"},
		gender: "N",
		heightm: 5,
		weightkg: 500,
		color: "Gray",
		eggGroups: ["Mineral"],
	},
	nucleozap:{
		num: -9012,
		species: "Nucelozap",
		types: ["Poison", "Electric"],
		baseStats: {hp: 100, atk: 110, def: 80, spa: 50, spd: 100, spe: 80},
		abilities: {0: "Speed Boost", 1: "Tinted Lens", H: "Guts"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 3.5,
		weightkg: 2,
		color: "Purple",
		eggGroups: ["Amorphous"],
	},
	cometier:{
		num: -9013,
		species: "Cometier",
		types: ["Cosmic", "Ice"],
		baseStats: {hp: 80, atk: 90, def: 80, spa: 90, spd: 80, spe: 150},
		abilities: {0: "Illuminate", H: "Adaptability"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 2,
		weightkg: 0.2,
		color: "Blue",
		eggGroups: ["Mineral"],
	},
	arceus: {
		inherit: true,
		otherFormes: ["arceusbug", "arceuscosmic", "arceusdark", "arceusdragon", "arceuselectric", "arceusfairy", "arceusfighting", "arceusfire", "arceusflying", "arceusghost", "arceusgrass", "arceusground", "arceusice", "arceuspoison", "arceuspsychic", "arceusrock", "arceussteel", "arceuswater"],
	},
	arceuscosmic: {
		num: 493,
		species: "Arceus-Cosmic",
		baseSpecies: "Arceus",
		forme: "Cosmic",
		formeLetter: "C",
		types: ["Cosmic"],
		gender: "N",
		baseStats: {hp: 120, atk: 120, def: 120, spa: 120, spd: 120, spe: 120},
		abilities: {0: "Multitype"},
		heightm: 3.2,
		weightkg: 320,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	silvally: {
		inherit: true,
		otherFormes: ["silvallybug", "silvallycosmic", "silvallydark", "silvallydragon", "silvallyelectric", "silvallyfairy", "silvallyfighting", "silvallyfire", "silvallyflying", "silvallyghost", "silvallygrass", "silvallyground", "silvallyice", "silvallypoison", "silvallypsychic", "silvallyrock", "silvallysteel", "silvallywater"],
	},
	silvallycosmic: {
		num: 773,
		species: "Silvally-Cosmic",
		baseSpecies: "Silvally",
		forme: "Cosmic",
		formeLetter: "C",
		types: ["Cosmic"],
		gender: "N",
		baseStats: {hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95},
		abilities: {0: "RKS System"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	cosmog: {
		inherit: true,
		types: ["Cosmic"],
	},
	cosmoem: {
		inherit: true,
		types: ["Cosmic"],
	},
	solgaleo: {
		inherit: true,
		types: ["Cosmic", "Steel"],
	},
	lunala: {
		inherit: true,
		types: ["Cosmic", "Ghost"],
	},
	starmie: {
		inherit: true,
		types: ["Water", "Cosmic"],
	},
	cleffa: {
		inherit: true,
		types: ["Fairy", "Cosmic"],
	},
	clefairy: {
		inherit: true,
		types: ["Fairy", "Cosmic"],
	},
	clefable: {
		inherit: true,
		types: ["Fairy", "Cosmic"],
	},
	solrock: {
		inherit: true,
		types: ["Rock", "Cosmic"],
	},
	lunatone: {
		inherit: true,
		types: ["Rock", "Cosmic"],
	},
	elgyem: {
		inherit: true,
		types: ["Cosmic", "Psychic"],
	},
	beheeyem: {
		inherit: true,
		types: ["Cosmic", "Psychic"],
	},
	necrozma: {
		inherit: true,
		types: ["Cosmic"],
	},
	deoxys: {
		inherit: true,
		types: ["Cosmic"],
	},
	deoxysspeed: {
		inherit: true,
		types: ["Cosmic"],
	},
	deoxysdefense: {
		inherit: true,
		types: ["Cosmic"],
	},
	deoxysattack: {
		inherit: true,
		types: ["Cosmic"],
	},
	altaar:{
		num: -,
		species: "Altaar",
		types: ["Dragon", "Ghost"],
		baseStats: {hp: 60, atk: 120, def: 45, spa: 75, spd: 60, spe: 90},
		abilities: {0: "Illusion"},
		genderRatio: {M: 0.875, F: 0.125},
		heightm: 3,
		weightkg: 181,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	badabing:{
		num: -,
		species: "Badabing",
		types: ["Normal", "Grass"],
		baseStats: {hp: 100, atk: 45, def: 50, spa: 45, spd: 60, spe: 60},
		abilities: {0: "Aftermath", 1: "Cloud Nine"},
		genderRatio: {M: 0.3, F: 0.7},
		heightm: 1.3,
		weightkg: 68,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	paxel:{
		num: -,
		species: "Paxel",
		types: ["Fighting"],
		baseStats: {hp: 65, atk: 60, def: 35, spa: 95, spd: 40, spe: 73},
		abilities: {0: "Vital Spirit", 1: "Stakeout"},
		genderRatio: {M: 0.9, F: 0.1},
		heightm: 2.1,
		weightkg: 48,
		color: "Orange",
		eggGroups: ["Undiscovered"],
	},	
};
