'use strict';

exports.BattlePokedex = {
	pyrix: {
		num: -9000,
		species: "Pyrix",
		types: ["Fire", "Fairy"],
		baseStats: {hp: 90, atk: 60, def: 85, spa: 120, spd: 55, spe: 90},
		abilities: {0: "Blaze", H: "Simple"},
		genderRatio: {M: 0.875, F: 0.125},
		heightm: 0.5,
		weightkg: 0.1,
		color: "Red",
		eggGroups: ["Amorphous"],
	},
	malwar: {
		num: -9001,
		species: "Malwar",
		baseForme: "Observer",
		types: ["Electric", "Normal"],
		baseStats: {hp: 100, atk: 75, def: 120, spa: 75, spd: 120, spe: 100},
		abilities: {0: "Frisk"},
		gender: "N",
		heightm: 1.7,
		weightkg: 1,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Mage", "Fighter"],
	},
	malwarmage: {
		num: -9001,
		species: "Malwar-Mage",
		baseSpecies: "Malwar",
		forme: "Mage",
		formeLetter: "M",
		types: ["Electric", "Psychic"],
		baseStats: {hp: 100, atk: 20, def: 120, spa: 160, spd: 50, spe: 100},
		abilities: {0: "Magical Power"},
		gender: "N",
		heightm: 1.7,
		weightkg: 1.5,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	malwarfighter: {
		num: -9001,
		species: "Malwar-Fighter",
		baseSpecies: "Malwar",
		forme: "Fighter",
		formeLetter: "F",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 100, atk: 160, def: 50, spa: 20, spd: 120, spe: 100},
		abilities: {0: "Huge Power"},
		gender: "N",
		heightm: 1.7,
		weightkg: 2,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	naucess: {
		num: -9002,
		species: "Naucess",
		types: ["Fairy", "Poison"],
		baseStats: {hp: 110, atk: 130, def: 60, spa: 60, spd: 60, spe: 75},
		abilities: {0: "Queenly Majesty", 1: "Iron Fist", H: "Firestarter"},
		gender: "F",
		heightm: 1,
		weightkg: 15,
		color: "Purple",
		eggGroups: ["Human-Like"],
	},
	chivalroot: {
		num: -9003,
		species: "Chivalroot",
		types: ["Grass", "Steel"],
		baseStats: {hp: 75, atk: 85, def: 120, spa: 30, spd: 110, spe: 80},
		abilities: {0: "Overgrow", H: "Justified"},
		genderRatio: {M: 0.875, F: 0.125},
		heightm: 3,
		weightkg: 100,
		color: "Green",
		eggGroups: ["Human-Like", "Field"],
	},
	poseident: {
		num: -9004,
		species: "Poseident",
		types: ["Water", "Fighting"],
		baseStats: {hp: 80, atk: 120, def: 75, spa: 60, spd: 55, spe: 110},
		abilities: {0: "Torrent", H: "Defiant"},
		genderRatio: {M: 0.875, F: 0.125},
		heightm: 1.5,
		weightkg: 5,
		color: "Blue",
		eggGroups: ["Water 1"],
	},
	zeron: {
		num: -9005,
		species: "Zeron",
		types: ["Ice", "Flying"],
		baseStats: {hp: 55, atk: 70, def: 95, spa: 120, spd: 80, spe: 55},
		abilities: {0: "Snow Cloak", 1: "Magic Guard", H: "Unaware"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 1.2,
		weightkg: 0.8,
		color: "Blue",
		eggGroups: ["Field"],
	},
	fusionvxn: {
		num: -9006,
		species: "Fusion: VxN",
		types: ["Grass", "Electric"],
		baseStats: {hp: 255, atk: 255, def: 255, spa: 255, spd: 255, spe: 255},
		abilities: {0: "Corruption"},
		gender: "N",
		heightm: 100,
		weightkg: 9999,
		color: "Unknown",
		eggGroups: ["Undiscovered"],
	},
	baroon:{
		num: -9007,
		species: "Baroon",
		types: ["Water", "Ground"],
		baseStats: {hp: 230, atk: 90, def: 150, spa: 110, spd: 90, spe: 70},
		abilities: {0: "Sturdy", 1: "Water Veil", H: "Rough Skin"},
		genderRatio: {M: 0.9, F: 0.1},
		heightm: 1.7,
		weightkg: 60,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	scarablade:{
		num: -9008,
		species: "Scarablade",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 50, atk: 95, def: 65, spa: 50, spd: 50, spe: 85},
		abilities: {0: "Swarm", H: "Adaptability"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 0.5,
		weightkg: 5,
		color: "Green",
		eggGroups: ["Bug", "Dragon"],
	},
	gigamole:{
		num: -9009,
		species: "Gigamole",
		types: ["Electric", "Ground"],
		baseStats: {hp: 60, atk: 105, def: 75, spa: 30, spd: 60, spe: 95},
		abilities: {0: "Static", H: "Serene Grace"},
		genderRatio: {M: 0.5, F: 0.5},
		heightm: 1.5,
		weightkg: 7,
		color: "Brown",
		eggGroups: ["Field"],
	},
};
